"""readding technique tables

Revision ID: 193439649a8
Revises: 40873ee056d0
Create Date: 2013-08-06 23:06:10.700936

"""

# revision identifiers, used by Alembic.
revision = '193439649a8'
down_revision = '40873ee056d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('techniques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itemtechniques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['technique_id'], ['techniques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itemtechniques')
    op.drop_table('techniques')
    ### end Alembic commands ###
