"""removing similarity tables (will persist via redis)

Revision ID: 1c41c3deac43
Revises: 193439649a8
Create Date: 2013-08-09 22:04:51.155098

"""

# revision identifiers, used by Alembic.
revision = '1c41c3deac43'
down_revision = '193439649a8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'menusimilarities')
    op.drop_table(u'restaurantsimilarities')
    op.drop_table(u'itemsimilarities')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'itemsimilarities',
    sa.Column(u'id', sa.INTEGER(), server_default="nextval('itemsimilarities_id_seq'::regclass)", nullable=False),
    sa.Column(u'item_id_1', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column(u'item_id_2', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column(u'score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id_1'], [u'items.id'], name=u'itemsimilarities_item_id_1_fkey'),
    sa.ForeignKeyConstraint(['item_id_2'], [u'items.id'], name=u'itemsimilarities_item_id_2_fkey'),
    sa.PrimaryKeyConstraint(u'id', name=u'itemsimilarities_pkey')
    )
    op.create_table(u'restaurantsimilarities',
    sa.Column(u'id', sa.INTEGER(), server_default="nextval('restaurantsimilarities_id_seq'::regclass)", nullable=False),
    sa.Column(u'restaurant_id_1', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column(u'restaurant_id_2', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column(u'score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id_1'], [u'restaurants.id'], name=u'restaurantsimilarities_restaurant_id_1_fkey'),
    sa.ForeignKeyConstraint(['restaurant_id_2'], [u'restaurants.id'], name=u'restaurantsimilarities_restaurant_id_2_fkey'),
    sa.PrimaryKeyConstraint(u'id', name=u'restaurantsimilarities_pkey')
    )
    op.create_table(u'menusimilarities',
    sa.Column(u'id', sa.INTEGER(), server_default="nextval('menusimilarities_id_seq'::regclass)", nullable=False),
    sa.Column(u'menu_id_1', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column(u'menu_id_2', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column(u'score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['menu_id_1'], [u'menus.id'], name=u'menusimilarities_menu_id_1_fkey'),
    sa.ForeignKeyConstraint(['menu_id_2'], [u'menus.id'], name=u'menusimilarities_menu_id_2_fkey'),
    sa.PrimaryKeyConstraint(u'id', name=u'menusimilarities_pkey')
    )
    ### end Alembic commands ###
