"""fixing similarity table names

Revision ID: 34f1486b7af4
Revises: 3897d5ead47a
Create Date: 2013-08-04 20:58:16.442590

"""

# revision identifiers, used by Alembic.
revision = '34f1486b7af4'
down_revision = '3897d5ead47a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
