"""fixing similarity relationships

Revision ID: 477d6fa53053
Revises: 34f1486b7af4
Create Date: 2013-08-04 21:07:27.835876

"""

# revision identifiers, used by Alembic.
revision = '477d6fa53053'
down_revision = '34f1486b7af4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
