"""adding category table to items

Revision ID: 4ce1b92c6b43
Revises: 215a18ff92e8
Create Date: 2013-08-03 16:35:14.862676

"""

# revision identifiers, used by Alembic.
revision = '4ce1b92c6b43'
down_revision = '215a18ff92e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'category')
    ### end Alembic commands ###
