"""added score column to similarity tables

Revision ID: 4ed747a7fba
Revises: 477d6fa53053
Create Date: 2013-08-04 21:33:35.331968

"""

# revision identifiers, used by Alembic.
revision = '4ed747a7fba'
down_revision = '477d6fa53053'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itemsimilarities', sa.Column('score', sa.Float(), nullable=False))
    op.add_column('menusimilarities', sa.Column('score', sa.Float(), nullable=False))
    op.add_column('restaurantsimilarities', sa.Column('score', sa.Float(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurantsimilarities', 'score')
    op.drop_column('menusimilarities', 'score')
    op.drop_column('itemsimilarities', 'score')
    ### end Alembic commands ###
