"""fosimilarity tables backref fix v3

Revision ID: 54e00ee4058f
Revises: 3c40bbe248a4
Create Date: 2013-08-05 11:29:21.394108

"""

# revision identifiers, used by Alembic.
revision = '54e00ee4058f'
down_revision = '3c40bbe248a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
